One/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('profile_setup/', views.profileSetup, name="profile_setup"),
    path('educator_dashboard/', views.educatorDashboard, name = 'educator_dashboard'),
    path('create_quiz/', views.create_quiz, name = "create_quiz"),
    path('create_question/',  views.create_question, name="create_question"),
    path('submit_question/', views.submit_question, name="submit_question"),
    path('student_dashboard/', views.studentDashboard, name="student_dashboard"),
    path('attend_quiz/<uuid:id2>/', views.attendQuiz, name='attend_quiz'),
    path('delete_quiz/', views.deleteQuiz, name='delete_quiz'),
   
]

quiz_application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'quiz application'

urlpatterns = [
    path('admin/quiz_application/', admin.site.urls),
    path('', include("One.urls")),
    path("account/", include("user.urls", namespace='account')), 
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

user/urls.py
from django.urls import path
from . import views

app_name = "user"   

urlpatterns = [
    
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name= "login"),
    path("logout/", views.logout, name= "logout"),
    path("change_password/", views.changePassword, name= "change_password"),
    path("set_reset_password_question/", views.setResetPasswordQuestion, name="set_reset_password_question"),
    path("forgot_password/", views.forgotPassword, name="forgot_password"),
    path("reset_password/<uuid:id>/", views.resetPassword, name="reset_password"),
    path("reset_password_check_qn/<uuid:id>/", views.resetPasswordCheckQn, name="reset_password_check_qn"),
    path("profile/", views.profilePage, name="profile"),
    path("two_factor/", views.twoFactor, name="two_factor"),
    path("delete_login_history/", views.deleteLoginHistory, name="delete_login_history"),
    path("create_ticket/", views.createTicket, name="create_ticket"),
    path('anonymous_contact/', views.anonymousContact, name='anonymous_contact')
    
]

templates/attend_quiz.html
{% extends "layout.html" %}
{% load static %}
{% block title %}<title>Attend Quiz</title>{% endblock %}
{% block content %}

    <div class="container">
        <p class="mt-5 h3 text-center mb-3">Attend the quiz</p>
        <form action="{% url 'attend_quiz' id2 %}" method="POST">

            {% csrf_token %}
            {% for items in question %}
                <p class="h4">{{items.question}}</p>
                <input type="radio" name="question_{{items.question}}" value="{{items.choice_one}}" required>
                <label class="lead"> {{items.choice_one}}</label><br>

                <input type="radio" name="question_{{items.question}}" value="{{items.choice_two}}">
                <label class="lead"> {{items.choice_two}}</label><br>

                <input type="radio" name="question_{{items.question}}" value="{{items.choice_three}}">
                <label class="lead"> {{items.choice_three}}</label><br>

                <input type="radio" name="question_{{items.question}}" value="{{items.choice_four}}">
                <label class="lead"> {{items.choice_four}}</label><br>
                <hr>
            {% endfor %}
            <div class="mt-5 mb-5">
                <button class="btn btn-primary d-grid gap-2 col-6 mx-auto fw-bold" type="submit">Submit quiz</button>
            </div>     
        </form>
    </div>
{% endblock %}

templates/create_question.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block title %}<title>Create Questions</title>{% endblock %}
{% block content %}

	<div class="container py-5">
		<p class="text-center h2 py-2">{{request.user.user_profile_educator.created_by_educator}}</p>
		<h6 class="mb-3 text-center">you have created {{request.user.user_profile_educator.created_by_educator.question_created.all.count}} question</h6>
			{% for items in request.user.user_profile_educator.created_by_educator.question_created.all %}
				<fieldset disabled>
					
					<div class="mb-3">
						<label for="disabledTextInput" class="h5 py-2">{{items.question}}</label>
						<div class="mb-2">
							<input type="text" id="disabledTextInput" class="form-control" placeholder="{{items.choice_one}}">
						</div>
						<div class="mb-2">
							<input type="text" id="disabledTextInput" class="form-control" placeholder="{{items.choice_two}}">
						</div>
						<div class="mb-2">
							<input type="text" id="disabledTextInput" class="form-control" placeholder="{{items.choice_three}}">
						</div>
						<div class="mb-2">
							<input type="text" id="disabledTextInput" class="form-control" placeholder="{{items.choice_four}}">
						</div>
						<p>Correct Answer: <b>{{items.correct_ans}} st choice</b> </p>
					</div>
				</fieldset>
				<hr>
			{% endfor %}
		

		{% if request.user.user_profile_educator.created_by_educator.question_created.all.count >= 10 %}
			<p class="text-center h6">you have created 10 questions, submit all questions</p>
			<form method="POST" action="{% url 'submit_question' %}">
				{% csrf_token %}
				<div class="d-grid gap-2 col-6 mx-auto mt-4">
					<button class="btn btn-primary fw-bold" type="submit">submit all questions</button>
				</div>
			</form>
		{% else %}
			<form method="POST" action="{% url 'create_question' %}">

				{% csrf_token %}
				{{form|crispy}}

				<div class="d-grid gap-2 col-6 mx-auto">
					<button class="btn btn-primary fw-bold" type="submit">add question</button>
				</div>
			</form>
		{% endif %}
	</div>

{% endblock %}

templates/create_quiz.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block title %}<title>Create Quiz</title>{% endblock %}
{% block content %}

	<div class="container py-5">
		
		<p class="text-center h3 py-3">Create Quiz</p>
		<form method="POST" action="{% url 'create_quiz'%}">

			{% csrf_token %}
			{{form|crispy}}         
		<button class="btn btn-primary fw-bold d-grid gap-2 col-6 mx-auto" type="submit">create quizz</button>
		</form>
		
	</div>

{% endblock %}

templates/educator_dashboard.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block title %}<title>Educator Dashboard</title>{% endblock %}
{% block content %}

  <!-- navbar -->
  <nav class="navbar navbar-dark bg-dark navbar-expand-md text-light navbar-nav-scroll fixed-top py-4" id="nav">
    <div class="container">
        <p class="navbar-brand"><span class="h3">Educator Dashboard</span></p>
        <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbar" id="navbar-toggler">
            <i class="fas fa-angle-down" id="toggle-button"></i>
        </button>
        <div class="navbar-collapse collapse" id="navbar">
            <ul class="navbar-nav ms-auto">  
                <li class="nav-item"><a href="{% url 'account:profile' %}" class="nav-link text-light lead">
                  <span id="nav-link">Profile</span></a></li>
            </ul>
        </div>
    </div>
  </nav>
  <!-- end navbar -->

  <div class="container py-5 mt-5">

    {% include "account/messages.html" %}

    {% if request.user.user_profile_educator.created_by_educator %}
      {% if request.user.user_profile_educator.created_by_educator.submitted_verify == True %}

        <!-- Modal publish quiz -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered">

            <div class="modal-content">
              <form method="POST" action="{% url 'educator_dashboard' %}">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Publish Quiz</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">

                  {% csrf_token %}
                  {{form|crispy}}
          
                </div>
                <div class="modal-footer">
                  <button type="submit" class="btn btn-primary d-grid gap-2 col-6 mx-auto fw-bold">Publish the quiz</button>
                </div>
              </form>
            </div>
          </div>
        </div>

        <!-- Modal2 delete quiz-->
        <div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              
                <form method="POST" action="{% url 'delete_quiz' %}">

                  {% csrf_token %}
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete Quiz</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <p>Are you sure want to delete this quiz?</p>                  
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary d-grid gap-2 col-5 mx-auto fw-bold" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger d-grid gap-2 col-5 mx-auto fw-bold">Yes</button>
                  </div>
                </form>
              
            </div>
          </div>
        </div>

        <h3 class="text-center mt-5">Quiz</h3>

        <div class="card mt-5">
          <div class="card-body">
            <div class="row d-flex align-items-center d-flex justify-content-center">
              <div class="col d-flex justify-content-lg-start justify-content-center mb-2">
                <h5 class="card-title">{{request.user.user_profile_educator.created_by_educator}}</h5>
              </div>
              {% if request.user.user_profile_educator.created_by_educator.publish_verify == True %}         
                  <div class="col-lg-auto d-flex justify-content-center mb-3">
                    <button type="button" class="btn btn-primary fw-bold" data-bs-toggle="modal"
                    data-bs-target="#exampleModal" disabled>published</button>
                  </div>                        
              {% else %}
                <div class="col-lg-auto d-flex justify-content-center mb-3">
                  <button type="button" class="btn btn-primary fw-bold" data-bs-toggle="modal"
                  data-bs-target="#exampleModal">Publish</button>
                </div>
              {% endif %}
              <div class="col-lg-auto d-flex justify-content-center mb-3"><button type="button" class="btn btn-danger fw-bold" data-bs-toggle="modal"
                data-bs-target="#exampleModal2">Delete Quiz</button>
              </div>
            </div>
          </div>
        </div>

        <hr class="mt-5">

        <h6>Student Marks</h6>
        {% for student in student_mark %}
          <p class="lead text-to-copy">{{student.student.user.email}} | {{student.mark}} Marks</p>
        {% endfor %}
        
        {% if student_mark %}
          <button onclick="copyText()" id="copy-button" class="btn btn-primary fw-bold d-grid gap-2 col-6 mx-auto mt-5">Copy Marks</button>
        {% endif %}
        
      {% elif request.user.user_profile_educator.created_by_educator.submitted_verify == False %}
        <p class="h3 text-center mt-5">You have already created a quiz - <b>{{request.user.user_profile_educator.created_by_educator}}</b> continue
          creating questions</p>
        <a href="{% url 'create_question'  %}" class="d-grid gap-2 col-6 mx-auto mt-5"><button class="btn btn-primary fw-bold" type="submit">create
            questions</button></a>
        <form action="{% url 'delete_quiz' %}" method="POST">
          {% csrf_token %}
          <button class="btn btn-danger d-grid gap-2 col-6 mx-auto mt-5 fw-bold" type="submit">Delete
            quiz</button></a>
        </form>
      {% endif %}
    {% else %}

      <p class="text-center h3 py-5">Welcome to Educator Dashboard</p>
    
      <a href="{% url 'create_quiz' %}" class="d-grid gap-2 col-6 mx-auto"><button class="btn btn-primary fw-bold" type="submit">create
          quizz</button></a>    
    {% endif %}

  </div>

  <script>
    function copyText() {

          let textElements = document.querySelectorAll(".text-to-copy");

          let concatenatedText = Array.from(textElements).map(function(element) {
              return element.innerText;
          }).join(' ');

          let tempElement = document.createElement('textarea');
          tempElement.value = concatenatedText;

          document.body.appendChild(tempElement);

          tempElement.select();
          document.execCommand('copy');

          document.body.removeChild(tempElement);
    
          document.getElementById("copy-button").innerText = "Copied!";
    }
  </script>

{% endblock %}

templates/layout.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    
    <!-- fontawesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css"
        integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    {% block title %}<title>Home</title>{% endblock %}

</head>
<body>

    {% block content %}  {% endblock%}

    <!-- bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    
</body>
</html>

templates/profile_setup.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block title %}<title>Profile Setup</title>{% endblock %}
{% block content %}

	<div class="container py-5">
		<h1 class="mb-5 text-center">Profile </h1>
		<form method="POST" action="{% url 'profile_setup' %}">

			{% csrf_token %}
			{{form|crispy}}

			<button class="btn btn-primary d-grid gap-2 col-6 mx-auto fw-bold mt-4" type="submit">submit</button>
		</form>
	</div>

{% endblock %}

templates/student_dashboard.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block title %}<title>Student Dashboard</title>{% endblock %}
{% block content %}

    <!-- navbar -->
    <nav class="navbar navbar-dark bg-dark navbar-expand-md text-light navbar-nav-scroll fixed-top py-4" id="nav">
        <div class="container">
            <p class="navbar-brand"><span class="h3">Student Dashboard</span></p>
            <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbar"
                id="navbar-toggler">
                <i class="fas fa-angle-down" id="toggle-button"></i>
            </button>
            <div class="navbar-collapse collapse" id="navbar">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a href="{% url 'account:profile' %}" class="nav-link text-light lead"><span
                        id="nav-link">Profile</span></a></li>
                    <li class="nav-item"><a href="" class="nav-link text-light lead"><span
                        id="nav-link">Contact</span></a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- end navbar -->

    <div class="container py-5">
        {% include "account/messages.html" %}
        <p class="h2 mt-5 text-center py-4 fw-bold">{{request.user}}</p>
        {% for items in users %}
            {% if items.created_by_educator.publish_verify == True %}
                {% if items.created_by_educator.year == request.user.user_profile_student.year and request.user.user_profile_student.course in items.created_by_educator.student_dept.all %}
                    <p class="h4">Educator: {{items.user.email}}</p>
                    <div class="card mt-3 mb-3">
                        <div class="card-body">
                            <div class="row row d-flex align-items-center d-flex justify-content-center">
                                <div class="col col d-flex justify-content-lg-start justify-content-center">
                                    <h5 class="card-title text-secondary fw-bold">{{items.created_by_educator}}</h5>
                                </div>                                               
                                {% if request.user.user_profile_student in items.created_by_educator.students_submitted.all %}
                                    {% for i in request.user.user_profile_student.student_quiz_mark.all %}                                                                                                                                                       
                                        {% if items.created_by_educator == i.quiz %}                                                                
                                            <div class="col-auto">
                                                <p class="fw-bold text-primary">{{i.mark}} Marks</p>
                                            </div>
                                        {% endif %}
                                    {% endfor %}
                                         
                                {% else %}
                                <div class="col-lg-auto d-flex justify-content-center mb-3">
                                    <a href="{% url 'attend_quiz' items.created_by_educator.id %}"> <button
                                            type="submit" class="btn btn-primary fw-bold">attend</button></a>
                                </div>
                                {% endif %}                                                                                           
                            </div>
                        </div>
                    </div>               
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}  